### ISSUE TITLE
Sync pos or rot of collide inside a rigid body

### ISSUE THREAD

**Issue by lidiamartinez** [Algoryx/AGXUnity#24]
Sync pos or rot of collide inside a rigid body.
I have a requirement in which I need to change collides inside a rigid body manually.
It's not optimal, but I prefer this better than having 8 rigid bodies and 7 constraints and moving them using forces. I don't need this to be accurate.

I have a RB with, say, 3 collide inside of it. I want to modify the position or rotation of them and tell the solver about it (sync), and update the inertia tensor and any information needed so that the output is correct in the next physics updates. As far as I know, no function is exposed publicly to sync in AGXUnity, and both receive a RB or sinc from the native object to the unity object. I cannot modify the position of a collide using code, no setPosition or setTransform is available either.

How would you do this?

**Comment by nmalg** [comment]
You're correct it's not exposed. I think it's hidden because it's most often undefined to set transforms in an active simulation. But of course there are cases where it can be defined and suitable.

I've made a script that changes the transform of a shape and synchronizes the changes. Hope this helps.

MoveShape.cs. Add to a game object with a shape component.
```c#
using UnityEngine;
using AGXUnity;
using AGXUnity.Collide;
using AGXUnity.Utils; // ToHanded extensions.

namespace Scripts
{
  public class MoveShape : ScriptComponent
  {
    private Shape m_shape = null;
    private RigidBody m_rb = null;

    protected override bool Initialize()
    {
      m_shape = GetComponent<Shape>();
      if ( m_shape == null ) {
        Debug.LogWarning( "Shape component not found.", this );
        return false;
      }

      m_rb = m_shape.GetComponentInParent<RigidBody>();
      if ( m_rb == null ) {
        Debug.LogWarning( "Shape is not part of rigid body.", this );
        return false;
      }

      return true;
    }

    protected override void OnEnable()
    {
      // Callback before stepForward is called.
      Simulation.Instance.StepCallbacks.PreStepForward += OnPreStep;
    }

    protected override void OnDisable()
    {
      if ( Simulation.HasInstance )
        Simulation.Instance.StepCallbacks.PreStepForward -= OnPreStep;
    }

    private void OnPreStep()
    {
      if ( m_shape == null || m_rb == null )
        return;

      var currPosition = m_shape.transform.localPosition;
      m_shape.transform.localPosition = new Vector3( currPosition.x,
                                                     2.0f * Mathf.Sin( (float)Simulation.Instance.Native.getTimeStamp() ),
                                                     currPosition.z );
      SyncNative();
    }

    private void SyncNative()
    {
      // AGXUnity.Collide.Shape transform corresponds to the native agxCollide::Geometry -
      // changing the local transform relative to the rigid body.
      m_shape.NativeGeometry.setLocalTransform( new agx.AffineMatrix4x4( m_shape.transform.localRotation.ToHandedQuat(),
                                                                         m_shape.transform.localPosition.ToHandedVec3() ) );
      // Update center of mass, inertia and mass of the rigid body.
      m_rb.Native.updateMassProperties( (uint)agx.MassProperties.AutoGenerateFlags.AUTO_GENERATE_ALL );
      // Propagates the changes to the Inspector.
      m_rb.MassProperties.SetDefaultCalculated( m_rb.Native );
    }
  }
}
```

**Comment by lidiamartinez** [comment]
Thanks a lot for this example.
Is it ok to do this while the rigid body is active? Will it cause any problem in the simulation?

**Comment by nmalg** [comment]
In general it's bad because when you move the body (or a part of it) the velocity is unknown to the solver. The solver uses the velocities to satisfy the constraints/contacts in a stable way, and when the velocity is "wrong", the constraints/contacts will be violated. The result is mostly strange looking simulations but can also lead to instabilities.

Eight rigid bodies and seven constraints sounds better to me 😉

**Comment by lidiamartinez** [comment]
Well. I made tests and it works like a charm. I just move the collides inside the rigid body and the shape of it is updated and behaves correctly. Well, that's something not critical right now, so we are happy with this 👍

**Comment by nmalg** [comment]
Very good!
