### ISSUE TITLE
Impossible to set Interations to -1 in solver settings

### ISSUE THREAD

**Issue by lidiamartinez** [Algoryx/AGXUnity#27]
This was allowed to set the default value. But we cannot use -1 anymore. Is this an error or we should set the default by hand as said in the tooltip of each field (16 and 7)?

**Comment by nmalg** [comment]
A "Reset"-button feature is more tempting than implicit -1, so for now you have to rely on the tooltip. I've created an internal feature request for resetting values to default. Thanks!

**Comment by lidiamartinez** [comment]
Cool. Updating AGX Unity in our project broke the settings because the -1 were translated to 0, so no collisions were happening. We had to set it to the default value by hand. Thanks!
