### ISSUE TITLE
Crash when DLL not recognized

### ISSUE THREAD

**Issue by lidiamartinez** [Algoryx/AGXUnity#29]
There are some problems with the version of my dll in the project, but I'm having different crashes on the project using AGXUnity last version in 2017, last AGXUnity version. 

Duing the shutdown of AGX and other example, in case this is useful for you.

[crash_AGX2.txt](https://github.com/Algoryx/AGXUnity/files/2614978/crash_AGX2.txt)
[crash_AGX.txt](https://github.com/Algoryx/AGXUnity/files/2614980/crash_AGX.txt)

I'll fix this by hand on the file system
Thanks

**Comment by nmalg** [comment]
Is this related to our discussion in #28?

**Comment by lidiamartinez** [comment]
Indeed. But I just wanted to notify that these crashes are due to uncaught exceptions. Probably something that can be fixed somehow.  And yes, it is due to having the wrong dll OR having .NET set to 3.5   Thanks!

**Comment by nmalg** [comment]
Unfortunately no, I don't think we can catch it because we depend on agxDotNet.dll both in the script and editor assemblies. It means that we don't have any code executed when something goes wrong with loading agxDotNet.dll. Re-open this issue if you have a solution and thanks for the report!
