### ISSUE TITLE
Sensor rb splits merged objects

### ISSUE THREAD

**Issue by lidiamartinez** [Algoryx/AGXUnity#31]
We are using a sensor rigid body that changes the material of some items in the scene when touching them so that the contacts change the solver type to make it more robust in some parts of the interaction. This works nice, but we detected some caveats:

We are trying to improve the efficiency using merge/split on all rigid bodies we can. Since the rigid body that the sensor is touching can be merged, the merged object is woken up / split every frame the sensor is moving in contact with it.... and then, if you stop moving it, the touched object is merged again.

This generates a very nasty effect in which while you move the sensor over any rigid body, the collides start offseting slowly separating from each other more and more (subtle but very visible). If you leave, then, the split on grativy option will bring them together again. If this is not set, they stay flying in the world.

Is the sensor colliding the rigid body and waking up / splitting it everyframe the sensor moves over it? Why is the sensor waking the rigid bodies up every frame?

**Comment by nmalg** [comment]
Thanks for the report!

Just to verify I fully understand: You have a rigid body which has a sensor, and this sensor is waking up merged objects without you doing anything (except that the rigid body is moving)?

**Comment by nmalg** [comment]
Ok, verified behavior in AGX Dynamics, and sensors should never affect merged objects.

I've fixed this issue in AGX Dynamics and it will be included in the next patch release. Contact us at support@algoryx.se if this patch is critical.

/Niklas
