### ISSUE TITLE
Import as agx prefab several times will create multiple copies of materials etc

### ISSUE THREAD

**Issue by vrguru** [Algoryx/AGXUnity#4]
It would be really nice if it would be possible to import as prefab multiple times and replacing the data for each imported object that already exists since before.

Right now I get multiple contactmaterials, materials etc...

Also, I really want to keep the Unity objects so that references to transforms, materials joints etc. are kept.
So only the underlying data, not the actual references should change.

**Comment by nmalg** [comment]
Are you sure the name of the .agx file is the same? The already created files should be updated with the new values and Unity is handling the prefab instances.

**Comment by vrguru** [comment]
Completely 100% positive.
Importing an .agx file once generate friction models and materials and contact materials

Importing same file again, generates additional materials with the same name.
So I need to delete data directory and generated prefab and re-import. Which leads to lost references.
